project:
  type: book
  output-dir: docs

book:
  title: "Biology 305: Biostatistics"
  author: "Dr. Jacob C. Cooper & Dr. Melissa Wuellner"
  date: "`r format(Sys.time(), '%d %B, %Y')`"
  chapters:
    - index.qmd
    - intro_to_r.qmd
    - descriptive_stats.qmd
    - visual.qmd
    - normality.qmd
    - exam2.qmd
    - probdist.qmd
    - ttest.qmd
    - two_ttest.qmd
    - anova1.qmd
    - anova2.qmd
    - cor_reg.qmd
    - final_exam.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib
csl: the-auk.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual